config/urls.py
from django.conf import settings
from django.urls import include, path
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from django.views import defaults as default_views

urlpatterns = [
    path("", TemplateView.as_view(template_name="pages/home.html"), name="home"),
    path(
        "about/", TemplateView.as_view(template_name="pages/about.html"), name="about"
    ),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("users/", include("rss_reader.users.urls", namespace="users")),
    path("feeds/", include("rss_reader.feeds.urls", namespace="feeds")),
    path("accounts/", include("allauth.urls")),
    # Your stuff: custom urls includes go here

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

rss_reader/feeds/urls.py
from django.urls import path
from .views import feeds, feed_create_view, feed_delete_view, feed_refresh_view, articles, article, \
    bookmark_article_view, article_delete

app_name = "feeds"
urlpatterns = [
    path("", view=feeds, name="feeds"),
    path("add/", view=feed_create_view, name="add_feed"),
    path("refresh/<int:pk>", view=feed_refresh_view, name="refresh_feed"),
    path("<int:pk>/", view=articles, name="articles"),
    path("article/<int:pk>", view=article, name="article"),
    path("bookmark/<int:pk>", view=bookmark_article_view, name="bookmark_article"),
    path("delete/<int:pk>", view=feed_delete_view, name="delete_feed"),
    path("articles/delete/<int:pk>", view=article_delete, name="delete_article"),
]

rss_reader/users/urls.py
from django.urls import path

from rss_reader.users.views import (
    user_redirect_view,
    user_update_view,
    user_detail_view,
)

app_name = "users"
urlpatterns = [
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<str:username>/", view=user_detail_view, name="detail"),
]

rss_reader/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db.models import CharField
from django.urls import reverse
from django.utils.translation import ugettext_lazy as _


class User(AbstractUser):

    # First Name and Last Name do not cover name patterns
    # around the globe.
    name = CharField(_("Name of User"), blank=True, max_length=255)

    def get_absolute_url(self):
        return reverse("users:detail", kwargs={"username": self.username})

rss_reader/feeds/forms.py
from django import forms
from .models import Feed


class AddFeedForm(forms.ModelForm):
    required_css_class = 'required'

    class Meta(forms.ModelForm):
        model = Feed
        fields = ['feed_url']
        widgets = {
            'feed_url': forms.TextInput(),
        }

rss_reader/users/forms.py
from django.contrib.auth import get_user_model, forms
from django.core.exceptions import ValidationError
from django.utils.translation import ugettext_lazy as _

User = get_user_model()


class UserChangeForm(forms.UserChangeForm):
    class Meta(forms.UserChangeForm.Meta):
        model = User


class UserCreationForm(forms.UserCreationForm):

    error_message = forms.UserCreationForm.error_messages.update(
        {"duplicate_username": _("This username has already been taken.")}
    )

    class Meta(forms.UserCreationForm.Meta):
        model = User

    def clean_username(self):
        username = self.cleaned_data["username"]

        try:
            User.objects.get(username=username)
        except User.DoesNotExist:
            return username

        raise ValidationError(self.error_messages["duplicate_username"])

rss_reader/feeds/views.py
from .models import Feed, Article
from .forms import AddFeedForm
from django.contrib.auth import get_user_model
from .tasks import parse_and_store_feed
from django.http import HttpResponseForbidden
from django.shortcuts import redirect, get_object_or_404
from django.core.exceptions import ObjectDoesNotExist

from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.views.generic import CreateView, ListView, DeleteView, RedirectView, DetailView
from .constants import ARTICLE_READ, ARTICLE_UNREAD
from django.utils.translation import ugettext_lazy as _
from django_celery_beat.models import PeriodicTask

User = get_user_model()


class FeedListView(LoginRequiredMixin, ListView):
    model = Feed
    template_name = "feeds/feed_list.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = AddFeedForm

        # TODO: Write better/raw query and load only needed list of Objects.
        user = User.objects.get(username=self.request.user.username)
        feeds_list = Feed.objects.filter(user=user)

        context['feeds'] = feeds_list

        return context

    def get_object(self):
        return User.objects.get(username=self.request.user.username)


feeds = FeedListView.as_view()


class FeedCreateView(LoginRequiredMixin, CreateView):
    model = Feed
    form_class = AddFeedForm
    template_name = "feeds/add_feed.html"

    def get_object(self, user: User):
        try:
            feed_url = self.request.POST["feed_url"]
            feed_url = feed_url.replace("http", "https")
            return Feed.objects.get(feed_url=feed_url, user=user)
        except ObjectDoesNotExist:
            return False

    def post(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return HttpResponseForbidden()

        form = self.get_form()
        user = User.objects.get(username=request.user.username)
        self.object = self.get_object(user)

        if not form.is_valid():
            return self.form_invalid(form)

        if self.object:
            error_message = {
                "duplicate_feed_url":
                    _("This feed url has already been added.")
            }
            return HttpResponseForbidden(error_message["duplicate_feed_url"])

        # TODO: Write better/raw query and load only one Object.
        feed_url = form.cleaned_data['feed_url']
        parse_and_store_feed.delay(feed_url=feed_url, user_id=user.id)

        return self.get_success_url()

    def get_success_url(self):
        return redirect("/feeds/")


feed_create_view = FeedCreateView.as_view()


class FeedDeleteView(LoginRequiredMixin, DeleteView):
    model = Feed
    success_url = reverse_lazy("feeds:feeds")

    def get_context_data(self, *args, **kwargs):
        context = super(FeedDeleteView, self).get_context_data(**kwargs)
        # TODO: Write better/raw query and load only a list of Objects needed.
        user = get_object_or_404(User, username=self.request.user.username)
        feed = get_object_or_404(Feed, pk=self.kwargs.get('pk'), user=user)

        try:
            PeriodicTask.objects.filter(
                name=f"Automatic parse and update Feed {feed.pk} for user: {feed.user.username}",
                task="parse_and_store_feed").delete()
        except ObjectDoesNotExist:
            pass

        return context


feed_delete_view = FeedDeleteView.as_view()


class FeedRefreshView(LoginRequiredMixin, RedirectView):
    permanent = False
    query_string = True
    pattern_name = 'feeds:feeds'

    def get(self, request, *args, **kwargs):
        # TODO: Write better/raw query and load only one Object.
        feed = get_object_or_404(Feed, pk=kwargs['pk'])
        user = User.objects.get(username=request.user.username)
        parse_and_store_feed.delay(feed_url=feed.feed_url, user_id=user.id, feed_id=feed.id, force_update=True)

        return redirect("/feeds/")

    def get_redirect_url(self, *args, **kwargs):
        return super().get_redirect_url(*args, **kwargs)


feed_refresh_view = FeedRefreshView.as_view()


class ArticleBookmarkRedirectView(LoginRequiredMixin, RedirectView):
    permanent = False
    query_string = True
    pattern_name = 'feeds:articles'

    def get(self, request, *args, **kwargs):
        # TODO: Write better/raw query and load only one Object.
        user = User.objects.get(username=self.request.user.username)
        article_detail = get_object_or_404(Article, pk=self.kwargs.get('pk'))
        feed = get_object_or_404(Feed, pk=article_detail.feed.id, user=user)

        if article_detail.bookmark is False:
            article_detail.bookmark = True
        else:
            article_detail.bookmark = False

        article_detail.save(update_fields=['bookmark'])

        return redirect(f'/feeds/{feed.id}')

    def get_redirect_url(self, *args, **kwargs):
        return super().get_redirect_url(*args, **kwargs)


bookmark_article_view = ArticleBookmarkRedirectView.as_view()


class ArticlesListView(LoginRequiredMixin, ListView):
    model = Article
    template_name = "feeds/article_list.html"
    ordering = ['-created']

    def get_context_data(self, *args, **kwargs):
        context = super(ArticlesListView, self).get_context_data(*args, **kwargs)
        # TODO: Write better/raw query and load only a list of Objects needed.
        user = User.objects.get(username=self.request.user.username)
        feed = get_object_or_404(Feed, pk=self.kwargs.get('pk'), user=user)
        articles_list = Article.objects.filter(feed=feed)
        context['articles'] = articles_list

        return context


articles = ArticlesListView.as_view()


class ArticleDetailView(LoginRequiredMixin, DetailView):
    model = Article
    template_name = "feeds/article_detail.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # TODO: Write better/raw query and load only one Object.
        user = User.objects.get(username=self.request.user.username)
        article_detail = get_object_or_404(Article, pk=self.kwargs.get('pk'))
        feed = get_object_or_404(Feed, pk=article_detail.feed.id, user=user)

        if article_detail.state == ARTICLE_UNREAD:
            article_detail.state = ARTICLE_READ
            article_detail.save(update_fields=['state'])
            feed.count_unread = feed.count_unread - 1
            feed.save(update_fields=['count_unread'])

        context['article'] = article_detail

        return context


article = ArticleDetailView.as_view()


class ArticleDeleteView(LoginRequiredMixin, DeleteView):
    model = Article
    success_url = reverse_lazy("feeds:articles")

    def get(self, request, *args, **kwargs):
        # TODO: Write better/raw query and load only one Object.
        user = User.objects.get(username=self.request.user.username)
        article_detail = get_object_or_404(Article, pk=self.kwargs.get('pk'))
        feed = get_object_or_404(Feed, pk=article_detail.feed.id, user=user)
        if article_detail.bookmark is not True:
            article_detail.delete()
            feed.count_unread = Article.objects.filter(
                feed=feed, state=ARTICLE_UNREAD).count()
            feed.count_total = Article.objects.filter(
                feed=feed).count()
            feed.save()

        return redirect(f'/feeds/{feed.id}')

    def get_redirect_url(self, *args, **kwargs):
        return super().get_redirect_url(*args, **kwargs)


article_delete = ArticleDeleteView.as_view()

rss_reader/users/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse
from django.views.generic import DetailView, RedirectView, UpdateView
from django.contrib import messages
from django.utils.translation import ugettext_lazy as _

User = get_user_model()


class UserDetailView(LoginRequiredMixin, DetailView):

    model = User
    slug_field = "username"
    slug_url_kwarg = "username"


user_detail_view = UserDetailView.as_view()


class UserUpdateView(LoginRequiredMixin, UpdateView):

    model = User
    fields = ["name"]

    def get_success_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})

    def get_object(self):
        return User.objects.get(username=self.request.user.username)

    def form_valid(self, form):
        messages.add_message(
            self.request, messages.INFO, _("Infos successfully updated")
        )
        return super().form_valid(form)


user_update_view = UserUpdateView.as_view()


class UserRedirectView(LoginRequiredMixin, RedirectView):

    permanent = False

    def get_redirect_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})


user_redirect_view = UserRedirectView.as_view()

rss_reader/templates/feeds/add_feed.html
{% extends "base.html" %}
{% load static %}

{% block title %}User: {{ user.username }}{% endblock %}

{% block content %}

<h2>Add Feed</h2>
<form class="form-horizontal" method="post" action="{% url 'feeds:add_feed' %}">
  <div class="row">
    <div class="col-sm-12">
      {% csrf_token %}
      {{ form }}
      <div class="control-group">
        <div class="controls">
          <button type="submit" class="btn btn-primary">Add</button>
        </div>
      </div>
    </div>
  </div>
</form>
{% endblock %}

rss_reader/templates/feeds/article_detail.html
{% extends "base.html" %}
{% load static %}
{% load tz %}

{% block title %}User: {{ user.username }}{% endblock %}

{% block content %}
<div class="container">
{% if user == request.user %}
<div class="row">
  <div><a href="{% url 'feeds:articles' pk=article.feed.id %}" class="btn btn-primary">Back</a></div>
  <div class="col-lg-12">
      <div>
        <div><i>Title:</i> {{ article.title }}</div>
        <div><i>Author:</i> {{ article.author }}</div>
        <div><i>Published:</i> {{ article.date | timezone:"Europe/Amsterdam" }}</div>
        <div><i>Status: </i>
        {% if article.state == 0 %}
            Unread
        {% else %}
            Read
        {% endif%}
          </div>
        <div><a target="_blank" href="{{ article.url }}">{{ article.url }}</a></div>
        <div><i>Leave a comment: </i><a target="_blank" href="{{ article.comments_url }}"> {{ article.comments_url }}</a></div>
      </div>
      <div>
        <div><i>Content:</i> {{ article.content }}</div>
      </div>
      {% if article.bookmark %}
            <div><a href="{% url 'feeds:bookmark_article' pk=article.pk %}" class="btn btn-danger">Remove Bookmark</a></div>
        {% else %}
            <div><a href="{% url 'feeds:bookmark_article' pk=article.pk %}" class="btn btn-success">Add Bookmark</a></div>
        {% endif %}
  </div>

</div>
{% endif %}


</div>
{% endblock content %}

rss_reader/templates/feeds/article_list.html
{% extends "base.html" %}
{% load static %}
{% load tz %}

{% block title %}User: {{ user.username }}{% endblock %}

{% block content %}
<div class="container-fluid">
{% if user == request.user %}
<div class="row">

  <div class="col-lg-12">
    <table class="table table-lg">
      <thead>
      <tr>
        <th scope="col"><a href="{% url 'feeds:feeds' %}" class="btn btn-primary">Back</a></th>
        <th scope="col">#</th>
        <th scope="col">Title</th>
        <th scope="col">Author</th>
        <th scope="col">Date</th>
        <th scope="col">URL</th>
        <th scope="col">Leave a comment</th>
        <th scope="col">State</th>
        <th scope="col">Bookmark</th>
        <th scope="col">Actions</th>

      </tr>
      </thead>
      <tbody>
      {% for article in articles %}
      <tr>
        <td></td>
        <td>{{ article.id }}</td>
        <td><a  href="{% url 'feeds:article' pk=article.pk %}">{{ article.title }}</a></td>
        <td>{{ article.author }}</td>

        <td>{{ article.date | timezone:"Europe/Paris" }}</td>
        <td><a target="_blank" href="{{ article.url }}">{{ article.url }}</a></td>

        <td><a target="_blank" href="{{ article.comments_url }}">{{ article.comments_url }}</a></td>

        {% if article.state == 0 %}
            <td>Unread</td>
        {% else %}
            <td>Read</td>
        {% endif%}

        {% if article.bookmark %}
            <td><a href="{% url 'feeds:bookmark_article' pk=article.pk %}" class="btn btn-danger">Remove Bookmark</a></td>
            <td><span></span></td>
        {% else %}
            <td><a href="{% url 'feeds:bookmark_article' pk=article.pk %}" class="btn btn-success">Add Bookmark</a></td>
            <td><a href="{% url 'feeds:delete_article' pk=article.pk %}" class="btn btn-warning">Remove</a></td>
        {% endif %}
      </tr>
      {% endfor %}
      <tr>
      </tbody>
    </table>
  </div>

</div>
{% endif %}


</div>
{% endblock content %}

rss_reader/templates/feeds/edit_feed.html
{% extends "base.html" %}
{% load static %}

{% block title %}User: {{ user.username }}{% endblock %}

{% block content %}

<h2>Add Feed</h2>
<form class="form-horizontal" method="post" action="{% url 'feeds:edit_feed' %}">
  {% csrf_token %}
  {{ form }}
  <div class="control-group">
    <div class="controls">
      <button type="submit" class="btn btn-primary">Add</button>
    </div>
  </div>
</form>
{% endblock %}

rss_reader/templates/feeds/feed_confirm_delete.html
{% extends "base.html" %}
{% load static %}

{% block title %}User: {{ user.username }}{% endblock %}

{% block modal %}

<form method="post" class="form-horizontal">{% csrf_token %}
  <div class="control-group">
    <div class="controls">
      <p>Are you sure you want to delete RSS Feed "{{ object.feed_url }}"?</p>
      <input class="btn btn-info half-input" style="width: 10%" type="submit" value="Confirm">
      <a class="btn btn-danger" href="{% url 'feeds:feeds' %}">
         Cancel
      </a>

    </div>
  </div>
</form>

{% endblock %}

rss_reader/templates/feeds/feed_list.html
{% extends "base.html" %}
{% load static %}
{% load tz %}

{% block title %}User: {{ user.username }}{% endblock %}

{% block content %}
<div class="container-fluid">
{% if user == request.user %}
<div class="row">

  <div class="col-sm-12">
    <table class="table">
      <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Title</th>
        <th scope="col">URL</th>
        <th scope="col">Added</th>
        <th scope="col">Unread</th>
        <th scope="col">Last Updated</th>
        <th scope="col">Last Checked</th>
        <th scope="col">Status</th>
        <th scope="col">Next Check</th>
        <th scope="col">Actions</th>
      </tr>
      </thead>
      <tbody>
      {% for feed in feeds %}
      <tr>
        <td>{{ feed.id }}</td>

        <td><a href="{% url 'feeds:articles' pk=feed.pk %}">{{ feed.title }}</a></td>
        <td><a href="{% url 'feeds:articles' pk=feed.pk %}">{{ feed.feed_url }}</a></td>

        <td>{{ feed.created | timezone:"Europe/Amsterdam" }}</td>

        <td>{{ feed.count_unread }}/{{ feed.count_total }}</td>
        <td>{{ feed.last_updated | timezone:"Europe/Amsterdam" }}</td>
        <td>{{ feed.last_checked | timezone:"Europe/Amsterdam" }}</td>

        {% if feed.is_active %}
            {% if feed.error %}
                <td>Problem</td>
            {% else %}
                <td>Active</td>
            {% endif %}
        {% else %}
            <td><img src="{{ STATIC_URL }}/images/favicons/favicon.png" alt="Inactive" title="Inactive"></td>
        {% endif %}

          <td>{{ feed.next_check | timezone:"Europe/Amsterdam" | default:"As soon as possible" }}</td>
          <td>
            <a href="{% url 'feeds:refresh_feed' pk=feed.pk %}" class="btn btn-primary">Refresh</a>
            <a href="{% url 'feeds:delete_feed' pk=feed.pk %}" class="btn btn-danger">Delete</a>
          </td>
      </tr>

      {% endfor %}
      <tr>
      </tbody>
    </table>

    {% include "feeds/part/add_feed.html" %}
  </div>

</div>
{% endif %}


</div>
{% endblock content %}